services:
  hll-geofences:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hll-geofences
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      - GO_ENV=production
    ports:
      - "8080:8080"
    restart: unless-stopped
